
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cofomvmhartb.ap-northeast-2.rds.amazonaws.com:3306/bob-friends?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: potatoes
    password: huge-potatoes
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: none
logging:
  level:
    web:
      debug
    org:
      hibernate: info

jwt:
  secret-key:
    access: "testfdalskasdlfk;ladsk;dflasljkjfdalkjfdlaskjfdlaksj"
    refresh: "testfdalskasdlfk;ladsk;dflasljkjfdalkjfdlaskjfd321321321231"
server:
  servlet:
    context-path: /api
