spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cofomvmhartb.ap-northeast-2.rds.amazonaws.com:3306/bob-friends?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: potatoes
    password: huge-potatoes
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          default_batch_fetch_size: 50
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
logging:
  level:
    web:
      debug
    org:
      hibernate: info

cloud:
  aws:
    s3:
      bucket: bob-friends
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

jwt:
  secret-key:
    access: "testfdalskasdlfk;ladsk;dflasljkjfdalkjfdlaskjfdlaksj"
    refresh: "testfdalskasdlfk;ladsk;dflasljkjfdalkjfdlaskjfd321321321231"
server:
  servlet:
    context-path: /api
